#!/usr/bin/env python3
"""Generated-launch parity test for the A200 sample.

Loads the launch file generated by ``clearpath_generator_robot`` for the
``test_a200`` sample, isolates the ``battery_state_estimator`` Node action
from the full LaunchDescription, runs it through ``launch.LaunchService`` in
the main thread, and replays a procedurally generated Power sweep into the
node's namespaced topic in a worker thread. The captured ``BatteryState``
stream is compared against expected states computed from the shipped
``config/battery_state_estimator/es20_12c.yaml`` plus the S2P1 cell layout.

This exercises the generator's actual emitted launch wiring — namespace,
``PathJoinSubstitution([FindPackageShare(...)...])`` parameter file
resolution, and overlay dict — end-to-end. No golden fixtures or per-scenario
overlays are written; everything is derived from the shipped config and the
per-battery sweep fixture.

Scenario: ``a200/ES20_12C_S2P1`` — matches the sample's
``platform: a200``, ``cell.num_series: 2``, ``cell.num_parallel: 1``.
"""

from __future__ import annotations

import importlib.util
import os
import threading
import time
from pathlib import Path

import pytest

import rclpy
from rclpy.node import Node
from rclpy.qos import (
    QoSDurabilityPolicy,
    QoSHistoryPolicy,
    QoSProfile,
    QoSReliabilityPolicy,
    qos_profile_sensor_data,
)

from launch import LaunchDescription, LaunchService
from launch_ros.actions import Node as LaunchNode

from clearpath_platform_msgs.msg import Power
from sensor_msgs.msg import BatteryState

from test_node_parity import (
    CONFIGURATIONS,
    PLATFORM_LAYOUTS,
    SETTLE_S,
    STARTUP_TIMEOUT_S,
    STEP_TIMEOUT_S,
    _battery_state_to_dict,
    _compare_step,
    _input_step_to_power,
    _stamp_key,
    build_power_steps,
    compute_expected_states,
    load_battery_config,
    load_input,
)


# --------------------------------------------------------------------------- #
# Scenario constants — pinned to the A200 sample
# --------------------------------------------------------------------------- #

THIS_DIR = Path(__file__).resolve().parent

PLATFORM = 'a200'
BATTERY = 'ES20_12C'
CONFIGURATION = 'S2P1'

NAMESPACE = 'a200_0000'
TARGET_EXECUTABLE = 'battery_state_estimator'
# Distinct from test_node_parity's '91' so the two test files can run
# back-to-back without DDS endpoint cross-talk.
ROS_DOMAIN_ID = '92'

# Workspace-relative path to the generated sample launch file. The
# clearpath_generator_robot_tests package installs samples to
# share/<pkg>/samples, but we read from source so the test runs without
# requiring an install step.
GENERATED_LAUNCH_REL = Path(
    'src/clearpath_generator_tests/clearpath_generator_robot_tests/samples/'
    'test_a200/platform/launch/platform-service.launch.py'
)


def _find_workspace_root(start: Path) -> Path | None:
    """Walk up from ``start`` looking for the workspace root (has src/clearpath_robot)."""
    for candidate in [start, *start.parents]:
        if (candidate / 'src' / 'clearpath_robot').is_dir():
            return candidate
    return None


# --------------------------------------------------------------------------- #
# Namespaced harness
# --------------------------------------------------------------------------- #

class _NamespacedHarness(Node):
    """Publish Power and capture BatteryState messages under a given namespace."""

    def __init__(self, namespace: str) -> None:
        super().__init__('battery_generated_launch_harness', namespace=namespace)
        reliable_qos = QoSProfile(
            reliability=QoSReliabilityPolicy.RELIABLE,
            durability=QoSDurabilityPolicy.VOLATILE,
            history=QoSHistoryPolicy.KEEP_LAST,
            depth=50,
        )
        self._pub = self.create_publisher(Power, 'platform/mcu/status/power', reliable_qos)
        self._captured: dict[tuple[int, int], BatteryState] = {}
        self._sub = self.create_subscription(
            BatteryState,
            'platform/bms/state',
            self._on_battery_state,
            qos_profile_sensor_data,
        )

    def _on_battery_state(self, msg: BatteryState) -> None:
        self._captured[_stamp_key(msg.header.stamp)] = msg

    def publisher(self):
        return self._pub

    def subscription_count(self) -> int:
        return self._pub.get_subscription_count()

    def publisher_count(self) -> int:
        return self._sub.get_publisher_count()

    def captured(self) -> dict[tuple[int, int], BatteryState]:
        return self._captured


def _wait_for_estimator(harness: _NamespacedHarness, timeout_s: float) -> None:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        rclpy.spin_once(harness, timeout_sec=0.1)
        if harness.subscription_count() >= 1 and harness.publisher_count() >= 1:
            break
    else:
        raise TimeoutError(
            f'estimator did not connect within {timeout_s:.1f}s '
            f'(sub_count={harness.subscription_count()}, pub_count={harness.publisher_count()})'
        )
    settle_deadline = time.monotonic() + SETTLE_S
    while time.monotonic() < settle_deadline:
        rclpy.spin_once(harness, timeout_sec=0.05)


def _publish_and_wait(harness: _NamespacedHarness, power_msg: Power,
                      timeout_s: float) -> BatteryState:
    key = _stamp_key(power_msg.header.stamp)
    harness.publisher().publish(power_msg)
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        rclpy.spin_once(harness, timeout_sec=0.05)
        if key in harness.captured():
            return harness.captured()[key]
    raise TimeoutError(f'no BatteryState received for stamp {key} within {timeout_s:.1f}s')


# --------------------------------------------------------------------------- #
# Launch-file loading and filtering
# --------------------------------------------------------------------------- #

def _load_generated_launch_description(launch_path: Path) -> LaunchDescription:
    """Import the generated launch file as a module and return its LaunchDescription."""
    spec = importlib.util.spec_from_file_location(
        'generated_platform_service_launch', str(launch_path)
    )
    if spec is None or spec.loader is None:
        raise ImportError(f'cannot load generated launch file: {launch_path}')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    if not hasattr(module, 'generate_launch_description'):
        raise AttributeError(
            f'{launch_path} does not define generate_launch_description()'
        )
    return module.generate_launch_description()


def _isolate_battery_node(ld: LaunchDescription, executable: str) -> LaunchNode:
    """Return the single Node action whose ``node_executable`` matches ``executable``."""
    matches: list[LaunchNode] = []
    for entity in ld.entities:
        if isinstance(entity, LaunchNode) and entity.node_executable == executable:
            matches.append(entity)
    if not matches:
        raise LookupError(
            f'no Node action with executable={executable!r} found in generated launch'
        )
    if len(matches) > 1:
        raise LookupError(
            f'expected exactly one Node action with executable={executable!r}, '
            f'found {len(matches)}'
        )
    return matches[0]


# --------------------------------------------------------------------------- #
# Test
# --------------------------------------------------------------------------- #

def test_generated_a200_launch_battery_parity() -> None:
    """Parity check: the A200 generated launch's battery_state_estimator vs node math."""
    workspace_root = _find_workspace_root(THIS_DIR)
    if workspace_root is None:
        pytest.skip('Could not locate workspace root (looking for src/clearpath_robot).')

    launch_path = workspace_root / GENERATED_LAUNCH_REL
    if not launch_path.is_file():
        pytest.skip(f'Generated launch file not found at {launch_path}')

    layout = PLATFORM_LAYOUTS[PLATFORM]
    num_series, num_parallel = CONFIGURATIONS[CONFIGURATION]

    battery_params = load_battery_config(BATTERY)
    input_fixture = load_input(BATTERY)

    power_steps = build_power_steps(input_fixture, layout, num_series)
    expected_states = compute_expected_states(
        power_steps, battery_params, layout, num_series, num_parallel)
    assert len(power_steps) == len(expected_states)

    # Load the generated launch file, isolate the battery_state_estimator Node,
    # and build a minimal LaunchDescription containing only it.
    full_ld = _load_generated_launch_description(launch_path)
    battery_node = _isolate_battery_node(full_ld, TARGET_EXECUTABLE)
    minimal_ld = LaunchDescription([battery_node])

    # Isolation env for both the launched subprocess and the in-process rclpy ctx.
    os.environ['ROS_DOMAIN_ID'] = ROS_DOMAIN_ID
    os.environ['ROS_LOCALHOST_ONLY'] = '1'

    launch_service = LaunchService()
    launch_service.include_launch_description(minimal_ld)

    # LaunchService can only be run from the main thread, so the rclpy
    # parity work runs in a worker thread and signals shutdown when done.
    worker_state: dict = {'captured': []}

    def _do_parity() -> None:
        try:
            rclpy.init()
            harness = _NamespacedHarness(NAMESPACE)
            try:
                _wait_for_estimator(harness, STARTUP_TIMEOUT_S)
                for step in power_steps:
                    power_msg = _input_step_to_power(step)
                    bs = _publish_and_wait(harness, power_msg, STEP_TIMEOUT_S)
                    worker_state['captured'].append(_battery_state_to_dict(bs))
            finally:
                harness.destroy_node()
                rclpy.shutdown()
        except BaseException as exc:  # noqa: BLE001 — surfaced after join
            worker_state['error'] = exc
        finally:
            launch_service.shutdown()

    worker = threading.Thread(target=_do_parity, daemon=True)
    worker.start()
    launch_service.run(shutdown_when_idle=False)
    worker.join(timeout=10.0)

    if 'error' in worker_state:
        raise worker_state['error']
    captured_dicts = worker_state['captured']

    all_mismatches: list[str] = []
    for idx, (actual, expected) in enumerate(zip(captured_dicts, expected_states)):
        all_mismatches.extend(_compare_step(actual, expected, idx))

    if all_mismatches:
        shown = '\n  '.join(all_mismatches[:20])
        more = '' if len(all_mismatches) <= 20 else f'\n  ... and {len(all_mismatches) - 20} more'
        pytest.fail(
            f'generated A200 launch parity: {len(all_mismatches)} mismatch(es) vs expected:\n'
            f'  {shown}{more}'
        )
