w200_0000:
  clearpath_diagnostic_updater:
    ros__parameters:
      serial_number: 'w200-0000'
      platform_model: 'w200'
      ros_distro: 'jazzy'
      latest_apt_firmware_version: '2.7.3'
      installed_apt_firmware_version: 'none'
      bms_state_rate: 10.0
      bms_state_tolerance: 0.15
      stop_status_rate: 0.0
      topics.sensors/imu_0/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_0/data.rate: 50.0
