#!/usr/bin/env python3

# Software License Agreement (BSD)
#
# @author    Roni Kreinin <rkreinin@clearpathrobotics.com>
# @copyright (c) 2023, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Redistribution and use in source and binary forms, with or without
# modification, is not permitted without the express permission
# of Clearpath Robotics.

import os

import rclpy
from rclpy.node import Node
from rclpy.qos import qos_profile_sensor_data

from clearpath_platform_msgs.msg import Power
from sensor_msgs.msg import BatteryState

from clearpath_config.clearpath_config import ClearpathConfig
from clearpath_config.common.types.platform import Platform
from clearpath_generator_common.common import BaseGenerator

from clearpath_diagnostics.battery_state.battery import Battery


class BatteryStateEstimator(Node):
    def __init__(self, setup_path='/etc/clearpath'):
        super().__init__('battery_state_estimator')
        self.setup_path = setup_path

        # Define paths
        self.config_path = os.path.join(self.setup_path, 'robot.yaml')

        # Parse YAML into config
        self.clearpath_config = ClearpathConfig(self.config_path)
        self.platform = self.clearpath_config.platform.get_platform_model()
        self.battery_model = self.clearpath_config.platform.battery.model
        self.battery_configuration = self.clearpath_config.platform.battery.configuration

        self.battery = Battery(
            battery=self.battery_model,
            configuration=self.battery_configuration,
            platform=self.platform)

        self.battery_state_pub = self.create_publisher(
            BatteryState,
            'platform/bms/state',
            qos_profile_sensor_data)

        self.power_status_sub = self.create_subscription(
            Power,
            'platform/mcu/status/power',
            self.power_status_callback,
            qos_profile_sensor_data)

    def power_status_callback(self, msg: Power):
        self.battery.update(msg)
        self.battery_state_pub.publish(self.battery.msg)


def main():
    setup_path = BaseGenerator.get_args()
    rclpy.init()

    bsp = BatteryStateEstimator(setup_path)

    rclpy.spin(bsp)

    bsp.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
