cpr_generic_e/sensors/camera_4:
  intel_realsense:
    ros__parameters:
      camera_name: 'camera_4'
      camera_namespace: 'camera'
      serial_no: '0'
      usb_port_id: ''
      device_type: 'd435'
      config_file: ''
      json_file_path: ''
      initial_reset: False
      accelerate_gpu_with_glsl: False
      rosbag_filename: ''
      log_level: 'info'
      output: 'screen'
      enable_color: True
      rgb_camera.color_profile: '640,480,30'
      rgb_camera.color_format: 'RGB8'
      rgb_camera.enable_auto_exposure: True
      enable_depth: True
      enable_infra: False
      enable_infra1: False
      enable_infra2: False
      depth_module.depth_profile: '640,480,30'
      depth_module.depth_format: 'Z16'
      depth_module.infra_profile: '0,0,0'
      depth_module.infra_format: 'RGB8'
      depth_module.infra1_format: 'Y8'
      depth_module.infra2_format: 'Y8'
      depth_module.exposure: 8500
      depth_module.gain: 16
      depth_module.hdr_enabled: False
      depth_module.enable_auto_exposure: True
      depth_module.exposure.1: 7500
      depth_module.gain.1: 16
      depth_module.exposure.2: 1
      depth_module.gain.2: 16
      enable_sync: False
      enable_rgbd: False
      enable_gyro: False
      enable_accel: False
      gyro_fps: 0
      accel_fps: 0
      unite_imu_method: 0
      clip_distance: -2.0
      angular_velocity_cov: 0.01
      linear_accel_cov: 0.01
      diagnostics_period: 0.0
      publish_tf: True
      tf_publish_rate: 0.0
      pointcloud.enable: True
      pointcloud.stream_filter: 2
      pointcloud.stream_index_filter: 0
      pointcloud.ordered_pc: False
      pointcloud.allow_no_texture_points: False
      align_depth.enable: False
      colorizer.enable: False
      decimation_filter.enable: False
      spatial_filter.enable: False
      temporal_filter.enable: False
      disparity_filter.enable: False
      hole_filling_filter.enable: False
      hdr_merge.enable: False
      wait_for_device_timeout: -1.0
      reconnect_timeout: 6.0
      rgb_camera.profile: '640,480,30'
      depth_module.profile: '640,480,30'
