cpr_generic_e/sensors/imu_1:
  um6_driver:
    ros__parameters:
      port: '/dev/clearpath/imu'
      baud: 115200
      update_rate: 20
      mag_updates: True
      accel_updates: True
      zero_gyros: True
      frame_id: 'imu_1_link'
      linear_acceleration_stdev: 0.0392266
      angular_velocity_stdev: 0.001047
      orientation_x_stdev: 0.05236
      orientation_y_stdev: 0.05236
      orientation_z_stdev: 0.05236
      tf_ned_to_enu: True
      orientation_in_robot_frame: False
