# Deka DTM8A31 (24 V Sealed Lead-Acid)
/**:
  ros__parameters:
    technology: 8  # vrla
    cell:
      voltage: 24.0    # Nominal voltage per battery unit in V
      capacity: 50.0   # Capacity per battery unit in Ah
      num_series: 1
      num_parallel: 1
    lookup_table:
      voltages:    [23.20, 23.40, 23.80, 24.00, 24.40, 24.60, 24.80, 25.00, 25.10, 25.20, 25.30, 25.40]
      percentages: [ 0.00,  0.10,  0.20,  0.30,  0.40,  0.50,  0.60,  0.70,  0.80,  0.90,  0.95,  1.00]
