lms1xx:
  ros__parameters:
    intensity: false
    intensity_resolution_16bit: false
    min_ang: -2.35619
    max_ang: 2.35619
    frame_id: laser_link
    host: 192.168.131.20
    port: 2111
    publish_min_range_as_inf: false 
    message_monitoring_enabled: true       
    read_timeout_millisec_default: 5000     
    read_timeout_millisec_startup: 120000   
    read_timeout_millisec_kill_node: 150000 
    client_authorization_pw: F4724744   