cpr_generic_e:
  clearpath_diagnostic_updater:
    ros__parameters:
      serial_number: 'generic-e'
      platform_model: 'generic'
      ros_distro: 'jazzy'
      latest_apt_firmware_version: '2.7.3'
      installed_apt_firmware_version: 'none'
      bms_state_rate: 10.0
      bms_state_tolerance: 0.15
      topics.sensors/imu_0/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_0/data.rate: 20.0
      topics.sensors/lidar2d_0/scan.type: 'sensor_msgs/msg/LaserScan'
      topics.sensors/lidar2d_0/scan.rate: 40.0
      topics.sensors/lidar2d_1/scan.type: 'sensor_msgs/msg/LaserScan'
      topics.sensors/lidar2d_1/scan.rate: 40.0
      topics.sensors/lidar2d_2/scan.type: 'sensor_msgs/msg/LaserScan'
      topics.sensors/lidar2d_2/scan.rate: 40.0
      topics.sensors/lidar2d_3/scan.type: 'sensor_msgs/msg/LaserScan'
      topics.sensors/lidar2d_3/scan.rate: 40.0
      topics.sensors/lidar3d_0/scan.type: 'sensor_msgs/msg/LaserScan'
      topics.sensors/lidar3d_0/scan.rate: 20.0
      topics.sensors/lidar3d_0/points.type: 'sensor_msgs/msg/PointCloud2'
      topics.sensors/lidar3d_0/points.rate: 20.0
      topics.sensors/lidar3d_1/scan.type: 'sensor_msgs/msg/LaserScan'
      topics.sensors/lidar3d_1/scan.rate: 20.0
      topics.sensors/lidar3d_1/points.type: 'sensor_msgs/msg/PointCloud2'
      topics.sensors/lidar3d_1/points.rate: 20.0
      topics.sensors/lidar3d_4/scan.type: 'sensor_msgs/msg/LaserScan'
      topics.sensors/lidar3d_4/scan.rate: 20.0
      topics.sensors/lidar3d_4/points.type: 'sensor_msgs/msg/PointCloud2'
      topics.sensors/lidar3d_4/points.rate: 20.0
      topics.sensors/lidar3d_5/scan.type: 'sensor_msgs/msg/LaserScan'
      topics.sensors/lidar3d_5/scan.rate: 20.0
      topics.sensors/lidar3d_5/points.type: 'sensor_msgs/msg/PointCloud2'
      topics.sensors/lidar3d_5/points.rate: 20.0
      topics.sensors/camera_0/color/image/compressed.type: 'sensor_msgs/msg/CompressedImage'
      topics.sensors/camera_0/color/image/compressed.rate: 20.0
      topics.sensors/camera_1/color/image/compressed.type: 'sensor_msgs/msg/CompressedImage'
      topics.sensors/camera_1/color/image/compressed.rate: 20.0
      topics.sensors/camera_2/color/image.type: 'sensor_msgs/msg/Image'
      topics.sensors/camera_2/color/image.rate: 40.0
      topics.sensors/camera_3/color/image.type: 'sensor_msgs/msg/Image'
      topics.sensors/camera_3/color/image.rate: 40.0
      topics.sensors/camera_4/color/image.type: 'sensor_msgs/msg/Image'
      topics.sensors/camera_4/color/image.rate: 30.0
      topics.sensors/camera_4/depth/image.type: 'sensor_msgs/msg/Image'
      topics.sensors/camera_4/depth/image.rate: 30.0
      topics.sensors/camera_4/points.type: 'sensor_msgs/msg/PointCloud2'
      topics.sensors/camera_4/points.rate: 30.0
      topics.sensors/camera_5/color/image.type: 'sensor_msgs/msg/Image'
      topics.sensors/camera_5/color/image.rate: 30.0
      topics.sensors/camera_5/depth/image.type: 'sensor_msgs/msg/Image'
      topics.sensors/camera_5/depth/image.rate: 30.0
      topics.sensors/camera_5/points.type: 'sensor_msgs/msg/PointCloud2'
      topics.sensors/camera_5/points.rate: 30.0
      topics.sensors/camera_6/color/image.type: 'sensor_msgs/msg/Image'
      topics.sensors/camera_6/color/image.rate: 30.0
      topics.sensors/camera_7/color/image.type: 'sensor_msgs/msg/Image'
      topics.sensors/camera_7/color/image.rate: 30.0
      topics.sensors/imu_0/mag.type: 'sensor_msgs/msg/MagneticField'
      topics.sensors/imu_0/mag.rate: 20.0
      topics.sensors/imu_1/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_1/data.rate: 20.0
      topics.sensors/imu_1/mag.type: 'sensor_msgs/msg/MagneticField'
      topics.sensors/imu_1/mag.rate: 20.0
      topics.sensors/imu_2/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_2/data.rate: 100.0
      topics.sensors/imu_2/mag.type: 'sensor_msgs/msg/MagneticField'
      topics.sensors/imu_2/mag.rate: 0.0
      topics.sensors/imu_3/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_3/data.rate: 100.0
      topics.sensors/imu_3/mag.type: 'sensor_msgs/msg/MagneticField'
      topics.sensors/imu_3/mag.rate: 0.0
      topics.sensors/imu_4/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_4/data.rate: 50.0
      topics.sensors/imu_4/data_raw.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_4/data_raw.rate: 50.0
      topics.sensors/imu_4/mag.type: 'sensor_msgs/msg/MagneticField'
      topics.sensors/imu_4/mag.rate: 50.0
      topics.sensors/imu_5/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_5/data.rate: 50.0
      topics.sensors/imu_5/data_raw.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_5/data_raw.rate: 50.0
      topics.sensors/imu_5/mag.type: 'sensor_msgs/msg/MagneticField'
      topics.sensors/imu_5/mag.rate: 50.0
      topics.sensors/imu_6/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_6/data.rate: 20.0
      topics.sensors/imu_6/mag.type: 'sensor_msgs/msg/MagneticField'
      topics.sensors/imu_6/mag.rate: 20.0
      topics.sensors/imu_7/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_7/data.rate: 20.0
      topics.sensors/imu_7/mag.type: 'sensor_msgs/msg/MagneticField'
      topics.sensors/imu_7/mag.rate: 20.0
      topics.sensors/gps_0/fix.type: 'sensor_msgs/msg/NavSatFix'
      topics.sensors/gps_0/fix.rate: 5.0
      topics.sensors/gps_1/fix.type: 'sensor_msgs/msg/NavSatFix'
      topics.sensors/gps_1/fix.rate: 5.0
      topics.sensors/gps_2/fix.type: 'sensor_msgs/msg/NavSatFix'
      topics.sensors/gps_2/fix.rate: 2.0
      topics.sensors/gps_3/fix.type: 'sensor_msgs/msg/NavSatFix'
      topics.sensors/gps_3/fix.rate: 1.0
      topics.sensors/gps_4/fix.type: 'sensor_msgs/msg/NavSatFix'
      topics.sensors/gps_4/fix.rate: 1.0
      topics.sensors/gps_5/fix.type: 'sensor_msgs/msg/NavSatFix'
      topics.sensors/gps_5/fix.rate: 1.0
      topics.sensors/gps_6/fix.type: 'sensor_msgs/msg/NavSatFix'
      topics.sensors/gps_6/fix.rate: 1.0
      topics.sensors/gps_7/fix.type: 'sensor_msgs/msg/NavSatFix'
      topics.sensors/gps_7/fix.rate: 10.0
      topics.sensors/gps_8/fix.type: 'sensor_msgs/msg/NavSatFix'
      topics.sensors/gps_8/fix.rate: 10.0
