#!/bin/bash
source /opt/ros/humble/setup.bash

# Generate and source setup.bash
ros2 run clearpath_generator_common generate_bash
source /etc/clearpath/setup.bash

# Generate discovery server start file
ros2 run clearpath_generator_common generate_discovery_server

# Generate description
ros2 run clearpath_generator_common generate_description

# Generate parameters
ros2 run clearpath_generator_robot generate_param

# Generate launch files
ros2 run clearpath_generator_robot generate_launch
