#!/bin/bash
# Software License Agreement (BSD)
#
# Author    Luis Camero <lcamero@clearpathrobotics.com>
# Copyright (c) 2024, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

source /opt/ros/jazzy/setup.bash

# Check if clearpath_generator_common package exists, if not look for it from a workspace
if [ ! -d "/opt/ros/jazzy/share/clearpath_generator_common" ]; then
  echo "/opt/ros/jazzy/share/clearpath_generator_common does not exist"
  echo "Expecting a workspace with clearpath_generator_common package"
  source /home/$USER/colcon_ws/install/setup.bash
fi

# Generate and source setup.bash
ros2 run clearpath_generator_common generate_bash
source /etc/clearpath/setup.bash

# Generate discovery server start file
ros2 run clearpath_generator_common generate_discovery_server

# Generate Zenoh router start file
ros2 run clearpath_generator_common generate_zenoh_router

# Generate vcan bridge start file
ros2 run clearpath_generator_common generate_vcan

# Generate description
ros2 run clearpath_generator_common generate_description

# Generate semantic description
ros2 run clearpath_generator_common generate_semantic_description

# Generate parameters
ros2 run clearpath_generator_robot generate_param

# Generate launch files
ros2 run clearpath_generator_robot generate_launch
