#!/bin/bash
# Software License Agreement (BSD)
#
# Author    Tony Baltovski <tbaltovski@clearpathrobotics.com>
# Copyright (c) 2024, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Create a temporary folder
temp_folder=$(mktemp -d)

# Get robot yaml file
if [ -e /etc/clearpath/robot.yaml ]; then
 sudo cp /etc/clearpath/robot.yaml "$temp_folder/robot.yaml"
fi


# CPR service logs
sudo journalctl -b 0 -u clearpath-platform >> $temp_folder/platform.log
sudo journalctl -b 0 -u clearpath-sensors >> $temp_folder/sensors.log
sudo journalctl -b 0 -u clearpath-robot >> $temp_folder/robot.log
sudo journalctl -b 0 -u clearpath-discovery >> $temp_folder/discovery.log
sudo journalctl -b 0 -u clearpath-manipulators >> $temp_folder/manipulators.log
sudo journalctl -b 0 -u clearpath-vcan >> $temp_folder/vcan.log
apt list --installed | grep clearpath >> $temp_folder/clearpath-packages.log
# ROS 2 diagnostics
ros2 doctor --report >> $temp_folder/doctor.log
ros2 topic list >> $temp_folder/topics.log
ros2 node list >> $temp_folder/nodes.log
env | grep 'ROS\|RMW' >> $temp_folder/env.log

# System diagnostics
sudo dmesg -T >> $temp_folder/dmesg.log
lsusb -t -v >> $temp_folder/usb.log
ls -lisah /dev/ >> $temp_folder/dev.log
cat /proc/cpuinfo >> $temp_folder/cpu-info.log
lshw >> $temp_folder/hw.log
cat /proc/meminfo | grep -E "MemTotal|MemFree|MemAvailable" >> $temp_folder/mem.log
cat /proc/loadavg >> $temp_folder/cpu-load.log

# Network diagnostics
ip a >> $temp_folder/ip.log
sudo cp -r /etc/netplan/ "$temp_folder/netplan/"
# Remove any lines containing the word 'password' (case insensitive) from netplan files
sudo sed -i '/\bpassword\b/Id' "$temp_folder/netplan/"*

# Get hostname
hostname=$(hostname)

# Get current date
current_date=$(date +"%Y-%m-%d")

# Compress log file into an archive
archive_name="${hostname}_${current_date}.tar.gz"
tar -czvf "$archive_name" -C "$temp_folder" .

# Move the archive to the home directory of the current user
mv "$archive_name" "$HOME/"

# Remove temporary folder
rm -r "$temp_folder"

echo "Log archived as: $HOME/$archive_name"
echo "Please review contents for any sensitive information before sharing."