#!/bin/bash
# Software License Agreement (BSD)
#
# Author    Luis Camero <lcamero@clearpathrobotics.com>
# Copyright (c) 2024, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

usage() { echo "Usage: $0 -p port -d device -v virtual -b baud" 1>&2; }
help()
{
  echo "-p: port to bind to [11412]";
  echo "-d: device to create [ttycan0]";
  echo "-v: virtual can device [vcan0]";
  echo "-b: baud level [s0 (10 Kbit/s), s1 (20 Kbit/s), s2 (50 Kbit/s), s3 (100 Kbit/s), s4 (125 Kbit/s), s5 (250 Kbit/s), s6 (500 Kbit/s), s7 (800 Kbit/s), s8 (1000 Kbit/s)]";
}

while getopts :p:d:v:b:h: o;
do
  case "${o}" in
    p) port=${OPTARG};;
    d) dev=${OPTARG};;
    v) vcan=${OPTARG};;
    b) baud=${OPTARG};;
    h | *) usage; help; exit 0;;
  esac
done

if [ -z "${port}" ] || [ -z "${dev}" ] || [ -z "${vcan}" ] || [ -z "${baud}" ]; then
  echo "Missing required arguments.";
  usage;
  help;
  exit 1;
fi

echo "Port: $port";
echo "Device: $dev";
echo "Virtual CAN: $vcan";
echo "Baud Rate: $baud";

socat udp4-datagram:192.168.131.2:$port,bind=:$port,range=192.168.131.1/24 pty,link=$dev &
sleep 1

slcand -o -c -F -$baud $dev $vcan &
sleep 1

ip link set $vcan txqueuelen 100
sleep 1

ip link set $vcan up
