r100_0000/sensors/lidar2d_0:
  urg_node:
    ros__parameters:
      angle_max: 3.141592653589793
      angle_min: -3.141592653589793
      ip_address: '192.168.131.20'
      ip_port: 10940
      serial_port: '/dev/ttyACM0'
      serial_baud: 115200
      laser_frame_id: 'lidar2d_0_laser'
      calibrate_time: False
      default_user_latency: 0.0
      diagnostics_tolerance: 0.05
      diagnostics_window_time: 5.0
      error_limit: 4
      get_detailed_status: False
      publish_intensity: False
      publish_multiecho: False
      cluster: 1
      skip: 0
